#!/bin/sh
#
# Increment or decrement volume by $cur using pulseaudio-ctl, display new volume with volnoti
#

# Increment to use.
incr=5

cur=$(pulseaudio-ctl full-status | grep -o '^[0-9]*')
case "$1" in
	"up")
		pulseaudio-ctl up $incr
		new=$(expr $cur + 5)
		if [[ $new -le 100 ]]; then
			volnoti-show $new
		else
			volnoti-show 100
		fi
	;;
	"down")
		pulseaudio-ctl down $incr
		new=$(expr $cur - 5)
		if [[ $new -ge 0 ]]; then
			volnoti-show $new
		else
			volnoti-show 0
		fi
	;;
	"mute")
        ismuted=$(pulseaudio-ctl full-status | grep -o '\s[a-z]*\s' | awk '{$1=$1;print}')
		case "$ismuted" in
            "yes")
                pactl set-sink-mute 0 toggle
                volnoti-show $cur
            ;;
            "no")
                pactl set-sink-mute 0 toggle
                volnoti-show -m
            ;;
            *)
                echo "error in mute"
                exit 1
        esac
	;;
	*)
		echo "Unsupported: \"$1\""
		exit 1
esac

