#!/usr/bin/env bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 5 mins, undim if user becomes active` \
  --timer 300 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .1' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
  `# lock after 2 more minute` \
  --timer 120 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; slock' \
    '' \
  `# Suspend after 1 more minute` \
  --timer 60 \
    'systemctl suspend' \
    ''
