#!/bin/bash

CURRENT=$(brightnessctl get)
MAX=$(brightnessctl max)
PERCENT=$(bc <<<"scale=2; $CURRENT / $MAX")
PERCENT=$(bc <<<"$PERCENT * 100")
volnoti-show -s /usr/share/pixmaps/volnoti-brightness/display-brightness-symbolic.svg $PERCENT
